version: 1.0

snow:
  - id: 546348 # Milo Genuine https://adobe.service-now.com/service_registry_portal.do#/service/546348

notifications:
  jira:
    default:
      project: MWPW # Mandatory
      filters:
        include:
          risk_rating: R5
      fields:
        assignee:
          name: blaishram
        customfield_11800: MWPW-140779 #epic link
        watchers:
          - casalino
          - jmichnow
          - mauchley
        labels:
          - "OriginatingProcess=Kodiak"
          - "security"
          - "kodiak-ticket"
        components:
          - name: "DevOps Security"
